server:
  port: 9090

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/db_xuki_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.zsy.xuki.entity
#showSql
logging:
  level:
    com:
      zsy:
        xuki:
          mapper : debug